#!/usr/bin/env bash
#
# sync.sh — propagate shared/ (the single source of truth) to every platform.
#
# Usage:
#   scripts/sync.sh            Copy shared files + regenerate manifests everywhere
#   scripts/sync.sh --check    Verify platforms match shared/ (exit 1 on drift)
#
# Never hand-edit the platform copies of shared files or manifests — edit
# shared/ and re-run this script. Platform manifests are generated by merging
# shared/manifest.base.json with shared/manifest.<platform>.json (objects merge
# recursively, null deletes a key, a "key+" array appends to the base array,
# anything else replaces).
#
# Targets:
#   Intention Chrome/                            shared files + fonts + icons + manifest (chrome)
#   Intention Firefox/                           shared files + fonts + icons + manifest (firefox)
#   Intention Apple/Shared (Extension)/Resources shared files + fonts + icons + manifest (apple)
#   Intention Android/app/src/main/assets/       shared files + fonts (no manifest — Android
#                                                loads these in a WebView and keeps its own
#                                                android-bridge.js / background.html)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$SCRIPT_DIR"

SHARED_DIR="shared"
CHROME_DIR="Intention Chrome"
FIREFOX_DIR="Intention Firefox"
APPLE_DIR="Intention Apple/Shared (Extension)/Resources"
ANDROID_DIR="Intention Android/app/src/main/assets"

# The synced set is derived from shared/ itself, so adding or removing a file
# there propagates without touching this script. manifest.*.json are merge
# inputs (never copied verbatim) and icons are handled separately below.
SHARED_FILES=()
while IFS= read -r f; do
  SHARED_FILES+=("$f")
done < <(cd "$SHARED_DIR" && find . -maxdepth 1 -type f \
  ! -name 'manifest.*.json' ! -name 'icon*.png' ! -name '.*' \
  | sed 's|^\./||' | LC_ALL=C sort)

ICON_FILES=()
while IFS= read -r f; do
  ICON_FILES+=("$f")
done < <(cd "$SHARED_DIR" && find . -maxdepth 1 -type f -name 'icon*.png' \
  | sed 's|^\./||' | LC_ALL=C sort)

if [[ ${#SHARED_FILES[@]} -eq 0 ]]; then
  echo "✗ No shared files found in $SHARED_DIR/ — refusing to sync" >&2
  exit 1
fi

CHECK=false
if [[ "${1:-}" == "--check" ]]; then
  CHECK=true
elif [[ -n "${1:-}" ]]; then
  echo "Unknown argument: $1" >&2
  echo "Usage: scripts/sync.sh [--check]" >&2
  exit 2
fi

DRIFT=()
ORPHANS=()

# place <src> <dest> — copy src to dest, or in --check mode record drift
# (covers both a stale copy and a missing one).
place() {
  local src="$1" dest="$2"
  if $CHECK; then
    if ! cmp -s "$src" "$dest"; then
      DRIFT+=("$dest")
    fi
  else
    mkdir -p "$(dirname "$dest")"
    cp "$src" "$dest"
  fi
}

# sweep_orphans <dest_dir> <allowed...> — find files in dest_dir that are no
# longer part of the synced set (a file deleted from shared/ leaves its copies
# behind otherwise). In --check mode record them; in sync mode remove them.
sweep_orphans() {
  local dest_dir="$1"; shift
  local allowed=("$@") f name a known
  for f in "$dest_dir"/*; do
    [[ -f "$f" ]] || continue
    name="$(basename "$f")"
    known=false
    for a in "${allowed[@]}"; do
      [[ "$name" == "$a" ]] && { known=true; break; }
    done
    $known && continue
    if $CHECK; then
      ORPHANS+=("$f")
    else
      rm "$f"
      echo "  removed orphan: $f"
    fi
  done
  if [[ -d "$dest_dir/fonts" ]]; then
    for f in "$dest_dir/fonts"/*; do
      [[ -f "$f" ]] || continue
      name="$(basename "$f")"
      if [[ ! -f "$SHARED_DIR/fonts/$name" ]]; then
        if $CHECK; then
          ORPHANS+=("$f")
        else
          rm "$f"
          echo "  removed orphan: $f"
        fi
      fi
    done
  fi
}

# generate_manifest <platform> <outfile> — merge base + overlay into outfile.
generate_manifest() {
  local platform="$1" outfile="$2"
  python3 - "$SHARED_DIR/manifest.base.json" "$SHARED_DIR/manifest.$platform.json" "$outfile" <<'PY'
import json, sys

def merge(base, overlay):
    out = dict(base)
    for k, v in overlay.items():
        if k.endswith('+'):
            # "key+" appends to the base array instead of replacing it, so an
            # overlay can add (e.g.) one permission without silently dropping
            # any permission later added to the base.
            key = k[:-1]
            merged = list(out.get(key) or [])
            merged += [x for x in v if x not in merged]
            out[key] = merged
        elif v is None:
            out.pop(k, None)
        elif isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = merge(out[k], v)
        else:
            out[k] = v
    return out

with open(sys.argv[1]) as f: base = json.load(f)
with open(sys.argv[2]) as f: overlay = json.load(f)
with open(sys.argv[3], 'w') as f:
    json.dump(merge(base, overlay), f, indent=2)
    f.write('\n')
PY
}

sync_platform() {
  # extra_files: platform-specific files that legitimately live alongside the
  # synced copies and must survive the orphan sweep.
  local dest_dir="$1" manifest_platform="$2" # manifest_platform empty = no manifest/icons
  shift 2
  local extra_files=("$@")

  for f in "${SHARED_FILES[@]}"; do
    place "$SHARED_DIR/$f" "$dest_dir/$f"
  done

  for font in "$SHARED_DIR"/fonts/*; do
    place "$font" "$dest_dir/fonts/$(basename "$font")"
  done

  # ${arr[@]+...} guards empty-array expansion under set -u on bash 3.2 (macOS)
  local allowed=("${SHARED_FILES[@]}" ${extra_files[@]+"${extra_files[@]}"})
  if [[ -n "$manifest_platform" ]]; then
    for f in "${ICON_FILES[@]}"; do
      place "$SHARED_DIR/$f" "$dest_dir/$f"
    done
    local tmp
    tmp="$(mktemp)"
    generate_manifest "$manifest_platform" "$tmp"
    place "$tmp" "$dest_dir/manifest.json"
    rm -f "$tmp"
    allowed+=("${ICON_FILES[@]}" manifest.json)
  fi

  sweep_orphans "$dest_dir" "${allowed[@]}"
}

# env.txt is the gitignored dev-only key file (loadEnv() in options.js);
# android-bridge.js / background.html are Android's WebView scaffolding.
sync_platform "$CHROME_DIR" chrome env.txt
sync_platform "$FIREFOX_DIR" firefox env.txt
sync_platform "$APPLE_DIR" apple env.txt
if [[ -d "Intention Android" ]]; then
  sync_platform "$ANDROID_DIR" "" android-bridge.js background.html
fi

if $CHECK; then
  if [[ ${#DRIFT[@]} -gt 0 || ${#ORPHANS[@]} -gt 0 ]]; then
    if [[ ${#DRIFT[@]} -gt 0 ]]; then
      echo "✗ Out of sync with shared/ (${#DRIFT[@]} stale or missing):" >&2
      for f in "${DRIFT[@]}"; do echo "    $f" >&2; done
    fi
    if [[ ${#ORPHANS[@]} -gt 0 ]]; then
      echo "✗ Orphaned copies no longer present in shared/ (${#ORPHANS[@]}):" >&2
      for f in "${ORPHANS[@]}"; do echo "    $f" >&2; done
    fi
    echo "  Edit shared/ (not the platform copies), then run: scripts/sync.sh" >&2
    exit 1
  fi
  echo "✓ All platforms in sync with shared/"
else
  echo "✓ Synced shared/ to Chrome, Firefox, Apple$([[ -d "Intention Android" ]] && echo ', Android')"
fi
