#!/usr/bin/env bash
#
# sync.sh — propagate shared/ (the single source of truth) to every platform.
#
# Usage:
#   scripts/sync.sh            Copy shared files + regenerate manifests everywhere
#   scripts/sync.sh --check    Verify platforms match shared/ (exit 1 on drift)
#
# Never hand-edit the platform copies of shared files or manifests — edit
# shared/ and re-run this script. Platform manifests are generated by merging
# shared/manifest.base.json with shared/manifest.<platform>.json (objects merge
# recursively, null deletes a key, anything else replaces).
#
# Targets:
#   Intention Chrome/                            shared files + fonts + icons + manifest (chrome)
#   Intention Firefox/                           shared files + fonts + icons + manifest (firefox)
#   Intention Apple/Shared (Extension)/Resources shared files + fonts + icons + manifest (apple)
#   Intention Android/app/src/main/assets/       shared files + fonts (no manifest — Android
#                                                loads these in a WebView and keeps its own
#                                                android-bridge.js / background.html)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$SCRIPT_DIR"

SHARED_DIR="shared"
CHROME_DIR="Intention Chrome"
FIREFOX_DIR="Intention Firefox"
APPLE_DIR="Intention Apple/Shared (Extension)/Resources"
ANDROID_DIR="Intention Android/app/src/main/assets"

SHARED_FILES=(
  content.css content.js options.css options.html options.js
  coaching.html coaching.js background.js prompts.js providers.js tracking.js
)
ICON_FILES=(icon16.png icon32.png icon48.png icon128.png)

CHECK=false
if [[ "${1:-}" == "--check" ]]; then
  CHECK=true
elif [[ -n "${1:-}" ]]; then
  echo "Unknown argument: $1" >&2
  echo "Usage: scripts/sync.sh [--check]" >&2
  exit 2
fi

DRIFT=()

# place <src> <dest> — copy src to dest, or in --check mode record drift.
place() {
  local src="$1" dest="$2"
  if $CHECK; then
    if ! cmp -s "$src" "$dest"; then
      DRIFT+=("$dest")
    fi
  else
    mkdir -p "$(dirname "$dest")"
    cp "$src" "$dest"
  fi
}

# generate_manifest <platform> <outfile> — merge base + overlay into outfile.
generate_manifest() {
  local platform="$1" outfile="$2"
  python3 - "$SHARED_DIR/manifest.base.json" "$SHARED_DIR/manifest.$platform.json" "$outfile" <<'PY'
import json, sys

def merge(base, overlay):
    out = dict(base)
    for k, v in overlay.items():
        if v is None:
            out.pop(k, None)
        elif isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = merge(out[k], v)
        else:
            out[k] = v
    return out

with open(sys.argv[1]) as f: base = json.load(f)
with open(sys.argv[2]) as f: overlay = json.load(f)
with open(sys.argv[3], 'w') as f:
    json.dump(merge(base, overlay), f, indent=2)
    f.write('\n')
PY
}

sync_platform() {
  local dest_dir="$1" manifest_platform="$2" # manifest_platform empty = no manifest/icons

  for f in "${SHARED_FILES[@]}"; do
    place "$SHARED_DIR/$f" "$dest_dir/$f"
  done

  for font in "$SHARED_DIR"/fonts/*; do
    place "$font" "$dest_dir/fonts/$(basename "$font")"
  done

  if [[ -n "$manifest_platform" ]]; then
    for f in "${ICON_FILES[@]}"; do
      place "$SHARED_DIR/$f" "$dest_dir/$f"
    done
    local tmp
    tmp="$(mktemp)"
    generate_manifest "$manifest_platform" "$tmp"
    place "$tmp" "$dest_dir/manifest.json"
    rm -f "$tmp"
  fi
}

sync_platform "$CHROME_DIR" chrome
sync_platform "$FIREFOX_DIR" firefox
sync_platform "$APPLE_DIR" apple
if [[ -d "Intention Android" ]]; then
  sync_platform "$ANDROID_DIR" ""
fi

if $CHECK; then
  if [[ ${#DRIFT[@]} -gt 0 ]]; then
    echo "✗ Out of sync with shared/ (${#DRIFT[@]} file(s)):" >&2
    for f in "${DRIFT[@]}"; do echo "    $f" >&2; done
    echo "  Edit shared/ (not the platform copies), then run: scripts/sync.sh" >&2
    exit 1
  fi
  echo "✓ All platforms in sync with shared/"
else
  echo "✓ Synced shared/ to Chrome, Firefox, Apple$([[ -d "Intention Android" ]] && echo ', Android')"
fi
